### ISSUE TITLE
Error when using remark plugins using external processes

### ISSUE THREAD

**Issue by cdfa** [rx-ts/eslint-mdx#73]
I don't know how much can be done about this, but using remark plugins that use external processes (like `remark-lint-no-dead-urls` or `remark-preset-github`) throws the following error:
```
$ npx eslint README.md
Error: `processSync` finished async. Use `process` instead
Occurred while linting /home/cdfa/Projects/react-turn-reveal/README.md:1
at assertDone (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/unified/8.4.0/node_modules/unified/index.js:459:11)
at Function.processSync (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/unified/8.4.0/node_modules/unified/index.js:391:5)
at Program (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint-plugin-mdx/1.5.5_eslint@6.4.0+react@16.9.0/node_modules/eslint-plugin-mdx/lib/es/rules/remark.js:35:44)
at listeners.(anonymous function).forEach.listener (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.4.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
at Array.forEach (<anonymous>)
at Object.emit (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.4.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
at NodeEventGenerator.applySelector (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.4.0/node_modules/eslint/lib/linter/node-event-generator.js:253:26)
at NodeEventGenerator.applySelectors (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.4.0/node_modules/eslint/lib/linter/node-event-generator.js:282:22)
at NodeEventGenerator.enterNode (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.4.0/node_modules/eslint/lib/linter/node-event-generator.js:296:14)
at CodePathAnalyzer.enterNode (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.4.0/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:646:23)
```

**Comment by JounQin** [comment]
Async plugin is not supported by Eslint now, it is an known issue, but we can only wait for Eslint support.

**Comment by JounQin** [comment]
Welcome to PR to add a notice about this is README, or just wait for the official support of async lint rules.

Feel free to reopen it if I'm incorrect.
